# Generated by Django 4.1.5 on 2023-02-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('camera_brand', models.CharField(choices=[('CANON', 'Canon'), ('SONY', 'Sony'), ('Casio', 'Casio')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(path='/images')),
                ('datetime_taken', models.DateTimeField()),
                ('file_type', models.CharField(choices=[('jpg', 'jpg'), ('jpeg', 'jpeg'), ('png', 'png'), ('heic', 'heic'), ('mp4', 'mp4'), ('mov', 'mov')], max_length=5)),
                ('camera_taken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='img_org.cameramodel')),
            ],
        ),
    ]
