# Generated by Django 4.1.5 on 2023-02-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_org', '0002_alter_file_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FilePathField(path='D:\\1. Files\\2. Projects\\0. Personal\\coding-projects\\image-organizer\\image_handler_api\\images'),
        ),
    ]
