[workspace]

members = [
    "imaginator_importer",
    "imaginator_app",
    "imaginator_egui",
    "imaginator_types",
    "adapters/postgres_adapter",
    "adapters/indradb_adapter"
]

resolver="2"

